services:
  - type: web
    name: paper-2-video-backend
    env: docker
    build:
      dockerfile: Dockerfile
      context: .
    command: uvicorn src.backend.server:app --host 0.0.0.0 --port 8000
    envVars:
      - key: ENVIRONMENT
        value: production
    disk:
      name: backend-disk
      mountPath: /app/src/backend/
      sizeGB: 10

  - type: web
    name: paper-2-video-frontend
    env: docker
    build:
      dockerfile: Dockerfile
      context: .
    command: streamlit run src/frontend/app.py
    envVars:
      - key: ENVIRONMENT
        value: production
    disk:
      name: frontend-disk
      mountPath: /app/src/frontend/
      sizeGB: 10
